### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by honzajavorek** [snikch/goodman#1]
Is there a way how to run tests for this repository?

I am working on testing infrastructure, which would be able to verify whether new Dredd releases work seamlessly with every hooks handler implementation. To include the `goodman` project, I need this repository to have [Travis CI](https://docs.travis-ci.com/user/languages/go) with the Cucumber test suite.

Without the Travis CI integration, I won't be able to test new Dredd releases with `goodman` and I won't be able to be confident about further integrating `goodman` with Dredd (dredd init, documentation, ...). And that would be a shame!

**Comment by snikch** [comment]
Hey there,

Theoretically you should be able to run `bundle exec cucumber` from the `cucumber` dir, however I'm not sure that they will pass. I'm working on a project at the moment that will make use of this hook handler, and I may find time to ensure all tests are passing as part of that work.

Not sure if that helps or not :)

**Comment by honzajavorek** [comment]
Great, I think that could work. I'll try to contribute with the Travis config.

**Comment by honzajavorek** [comment]
@snikch Do you think you can get to this any soon? We integrated Goodman to Dredd as first-class citizen with docs and `--language` command line parameter, but to keep it like that we need to be sure that everything works well together. If we can't add Goodman to our integration tests, we can't guarantee to Dredd users it will work for them.

**Comment by snikch** [comment]
I can't make any promises, but it's on my to do list. I'll get there but it would be dishonest to say it's a priority. Sorry I can't help much more at this point.

**Comment by ddelnano** [comment]
@honzajavorek WIP right now but opened it up so the progress can be [seen](https://github.com/snikch/goodman/pull/5).

**Comment by ddelnano** [comment]
@snikch in order to consider this closed can you turn on travis ci builds?  Is that already on?

**Comment by snikch** [comment]
@ddelnano I've made you a collaborator so you can get this working. I haven't worked with Travis in a very long time.

**Comment by ddelnano** [comment]
@snikch awesome thanks.  I'll get it setup.

**Comment by ddelnano** [comment]
@snikch I don't have access to the repo's settings which is where the integration gets added.

**Comment by snikch** [comment]
Damn, I hoped that wouldn't be an issue. What do you need me to do?

**Comment by ddelnano** [comment]
@snikch I think if you go to your travis' profile you will see all your repos and all you need to do it click this button.  Should look something like this.
<img width="1920" alt="screen shot 2016-06-02 at 5 05 45 pm" src="https://cloud.githubusercontent.com/assets/5855593/15761067/46c41cde-28e4-11e6-8aa5-99286f2671af.png">

**Comment by snikch** [comment]
Cool, done - and I've added the badge to the repo. Waiting for a build.

**Comment by snikch** [comment]
K, build failed on the root package.

**Comment by ddelnano** [comment]
Yea I am trying to debug what happened.

**Comment by ddelnano** [comment]
They pass locally on master
<img width="1920" alt="screen shot 2016-06-02 at 5 15 52 pm" src="https://cloud.githubusercontent.com/assets/5855593/15761346/ac957c28-28e5-11e6-97c9-4105f21d4e43.png">

**Comment by snikch** [comment]
This _may_ be related to that timeout we talked about yesterday. If the machines powering travis' builds are under or overpowered compared to your local env you could see different performance characteristics (or perhaps different networking) - so that sleep may not be long enough anymore. That's one idea anyway :D

**Comment by ddelnano** [comment]
@snikch the problem is a dredd bug that I encountered when getting the tests to pass.  I thought I made sure the api blueprint worked with it.

**Comment by ddelnano** [comment]
This is a javascript stack trace.
<img width="1259" alt="screen shot 2016-06-02 at 5 17 59 pm" src="https://cloud.githubusercontent.com/assets/5855593/15761407/f98c973c-28e5-11e6-999f-58770cb7bd25.png">

**Comment by ddelnano** [comment]
@snikch ah I know what is happening I modified my local node_modules to prevent this from happening 😅 .  This is definitely a dredd bug tho.

It crashes on this [line](https://github.com/apiaryio/dredd/blob/master/src/hooks-worker-client.coffee#L302) @honzajavorek you have any idea what is going on?  I will look into this further as well.

**Comment by ddelnano** [comment]
The compiled javascript looks like this, where it is obvious that it tries to get length property of undefined, like in the error message.

<img width="675" alt="screen shot 2016-06-02 at 5 27 14 pm" src="https://cloud.githubusercontent.com/assets/5855593/15761634/4b75441c-28e7-11e6-8706-312f29a1ef92.png">

**Comment by snikch** [comment]
`transactions[0]?.hooks_modifications` ?

**Comment by ddelnano** [comment]
@snikch the line numbers didn't match up because i was scrolling while vim was open so the relative numbering was not correct.  As you can see it happens in the for loop

Edit: Didn't mention that I updated the picture.

**Comment by snikch** [comment]
If #302 of the coffee was updated to `for mod, index in transactions[0]?.hooks_modifications` I think it would check for existence before looping.

**Comment by ddelnano** [comment]
Oh I see what you are saying.  Yea I agree that would fix the error but that loop is specifically there for [these](https://github.com/snikch/goodman/blob/master/features/execution_order.feature#L82-L89) assertions

**Comment by snikch** [comment]
Ah, ok. So this most likely is a bug in the Go side of things than the handler.

**Comment by ddelnano** [comment]
@snikch oops yea I wrote the test wrong.  I just checked with my php ones.  In the go tests I printed the string out when I am supposed to modify the transaction.   Will prepare a fix.

**Comment by honzajavorek** [comment]
The test is to check order of transactions. If the Dredd code crashes, it means it's poorly written as it doesn't count with exceptional situations, but the thing is that the test would basically fail anyway since for the test to pass the console.logs need to be executed. So if it's crashing, it means the test isn't passing.

**Comment by ddelnano** [comment]
@honzajavorek can this be considered closed now?  Travis build is working and I also have an example project with goodman and dredd working in #7

**Comment by honzajavorek** [comment]
Yes! We need to add Go to https://github.com/apiaryio/dredd/blob/master/scripts/test-hooks-handlers.coffee#L73, but that's just a nitpick.

**Comment by ddelnano** [comment]
@honzajavorek cool, I will take a look at that.
