### ISSUE TITLE
Modify the Request Path

### ISSUE THREAD

**Issue by qustavo** [snikch/goodman#16]
Hey, I'm trying to modify the request path inside a `Before()` hook, but it's not wokring, this is how the code looks like:

```
	h.Before("/resource/{id} > GET > 200 > application/json", func(t *trans.Transaction) {
                newId := createResource()
		uri := strings.Replace(t.FullPath, "xxx", newId, 1)
		t.FullPath = uri
		t.Request.URI = uri
	})
```
But dredd it's still calling `GET /resource/xxx`. Am I doing something wrong?

**Comment by ddelnano** [comment]
Not sure. I will have to make an example and see if I can reproduce what you are seeing since it seems what you are doing looks right. I probably won't have time until later tonight or tomorrow but I will post back when I do.

**Comment by qustavo** [comment]
I fix my issue by calling `h.BeforeAll()` and compare the `transaction.Name` against `/resource/{id} > GET > 200 > application/json`. No idea why.

**Comment by ddelnano** [comment]
Hm that is interesting. There must be a bug that doesn't use the mutated transaction for the Before hook. Thanks for the update.

**Comment by qustavo** [comment]
it might be, it's weird, I'll try to digg deeper

**Comment by qustavo** [comment]
my bad, sorry!

**Comment by ddelnano** [comment]
It works as expected?

**Comment by qustavo** [comment]
yes, I couldn't find why it wasn't working. I think is due to try to code on Sundays.

**Comment by ddelnano** [comment]
haha I feel you on that.  Well glad it is actually working properly.
