### ISSUE TITLE
Could releases be tagged?

### ISSUE THREAD

**Issue by gonzalo-bulnes** [snikch/goodman#18]
Hello again!

In the same line as #17 (using dependencies managers) but independently: could the goodman releases be tagged? (Please!)

Since I'm asking, could the release numbers adhere to the [Semantic Versioning][semver] conventions? That makes automated updates so much safer that it reduces drastically the  maintenance efforts related to dependencies management when using a [dependencies manager][depman].

I would also suggest a look at http://keepachangelog.com, I'm using it and I find that the extra work required maintain a change log is minimal ([example][example]). And it makes things much clearer, even for me as a maintainer.

  [depman]: https://github.com/golang/go/wiki/PackageManagementTools
  [semver]: http://semver.org
  [example]: https://github.com/gonzalo-bulnes/simple_token_authentication/commit/ce6279abf43071477b8e23a2340ee288ea3a97d3

**Comment by ddelnano** [comment]
Yea, I apologize for this not being tagged in the first place.  I am a little torn on where to start the versioning.  When I made large changes to the project as I said in #17 this was my first go project and since then I have learned alot about best practices.  That being said I would like to take a stab at reimplementing things but I have not made the time to do so.  I think I am leaning towards a pre 1.0 release.  

ping @snikch .  Not sure how you feel about all this.

**Comment by gonzalo-bulnes** [comment]
Semantic versioning does not attribute any kind of stability to the 0.x.x series ([anything can change anytime in the 0.x.x series][stable]), but tagging them allows to freeze the version when using dependencies managers (e.g. `govendor fetch github.com/snikch/goodman/cmd/govendor@=v0.1.0` using the [govendor syntax][govendor]). 

Once the dependencies manager knows that, you can run automatic updates safely - you won't get updates for the packages with frozen versions, but you'll get updates for everything than adheres to semantic versioning with a very low risk of issues.

On the other hand, if any package in your dependencies has no tags, your package manager has no clue, and automated updates will update the package without version constraint. Eventually the update will pull breaking changes in. In my experience, that often turns quickly in a "never update dependencies automatically" culture. Because dependencies inter-dependence is often complex, manual updates are rarely optimal, and as soon as you're a few versions behind in multiple packages it becomes very difficult to know what is safe to update and what is not. That's the primary issue addressed by Semantic Versioning.

So **just to clarify**, I'm not asking for the goodman API to be declared stable, I'm saying that making it's status understandable by a machine brings real value : )

Then, while in the 0.x.x series, a quick look at the `CHANGELOG` tells you if updating the version constraint in the dependencies manager is safe. It's a manual step, but the consequences of the constraint update will be taken care of automatically by the dependencies manager. I that sense I consider it a quick win.

  [govendor]: https://github.com/kardianos/govendor#package-specifier
  [stable]: http://semver.org/#spec-item-4

**Comment by ddelnano** [comment]
Yea i am familiar with semantic versioning just a little torn on where this stands. I will tag it tomorrow. Definitely going with 0.x.x. Thanks for bringing these issues up

**Comment by gonzalo-bulnes** [comment]
Thanks @ddelnano, sorry for the words overflow 😉

**Comment by ddelnano** [comment]
No worries :)

**Comment by ddelnano** [comment]
0.1.0 was tagged, closing this.

**Comment by snikch** [comment]
Sorry for jumping in after close but `0.1.0` makes perfect sense to me! Good stuff 👌
