### ISSUE TITLE
Add GitHub topics

### ISSUE THREAD

**Issue by honzajavorek** [snikch/goodman#20]
GitHub introduces [topics](https://github.com/blog/2309-introducing-topics). It would be nice if this repo had `dredd`, `go`, and `dredd-hooks`.

**Comment by ddelnano** [comment]
Hm even though I am able to push to this repo, I don't have the ability to add the hooks.  @snikch can you add those when you get the chance?

**Comment by ddelnano** [comment]
Hm even though I am able to push to this repo, I don't have the ability to add the hooks.  @snikch can you add those when you get the chance?

**Comment by snikch** [comment]
Done! Odd they don't give you permission to add topics when you're a collaborator - there aren't any permissions that can be granted etc.
