### ISSUE TITLE
Create Dockerfile for goodman

### ISSUE THREAD

**Issue by jamiehannaford** [snikch/goodman#34]
Would it be possible to create a Dockerfile with `dredd` and `goodman` installed (`npm` and `go` too) so folks can just do a `docker run` rather than having to manually install and configure things themselves?

**Comment by snikch** [comment]
Sounds like a great idea. PR's welcome!

**Comment by ddelnano** [comment]
@jamiehannaford I have done this before and the results can be meh imo. I don't necessarily think it works great out of the box for everyone and therefore don't think a general solution is necessarily useful.  I am blanking on exact details but I have a [dredd image](https://github.com/nowait-tools/docker-images/tree/master/alpine/dredd) I have used on node projects.

I'm assuming you want your app outside this docker container? Is this also containerized?  Will the hooks be populating other data stores?

**Comment by ddelnano** [comment]
I'm going to close this since the issue has been open for a while. We'd be happy to accept a contribution if someone were to give this a shot!
