### ISSUE TITLE
Hook files with flags

### ISSUE THREAD

**Issue by adamfdl** [snikch/goodman#39]
How do I alter the behavior of the hook files, provided by a specific flag? Say that I want to set the database connection to A if I am running it locally, and set it to database connection B if I am running it against a development server.

**Comment by ddelnano** [comment]
What about using environment variables? If I remember correctly you won't be able to alter the behavior via the cli since it would require dredd to have support for it. You can see from [here](https://dredd.org/en/latest/usage-cli.html#arguments) there are only certain "hook" related flags.

**Comment by adamfdl** [comment]
Ah I see, that settles it then. Thanks @ddelnano.
